name: "Reusable Distro Workflow"

on:
  workflow_call:
    inputs:
      distro:
        required: true
        type: string
      package_man:
        required: true
        type: string
      additional_packages:
        required: false
        type: string

defaults:
  run:
    shell: bash

jobs:
  reusable-workflow:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Make container name
        run: |
          input_distro=${{ inputs.distro }}
          distro_name_and_ver=$(echo input_distro | awk -F '/' '{print $NF}')
          container_name=${distro_name_and_ver/:/_}
          echo "CONTAINER_NAME=$container_name" >> $GITHUB_ENV
      
      - name: Check if additional package is needed by package manager
        run: |
          if [[ ${{ inputs.package_man }} == "apt" ]]; then
            echo "ADDITIONAL_PKG=libpam-systemd" >> $GITHUB_ENV
          else
            echo "ADDITIONAL_PKG=" >> $GITHUB_ENV
          fi
      
      - name: Add additional packages if passed as an input
        if: ${{ inputs.additional_packages }}
        run: |
          additional_packages_input=${{ inputs.additional_packages }}
          echo "ADDITIONAL_PKG=$ADDITIONAL_PKG $additional_packages_input" >> $GITHUB_ENV
      
      - name: Update container
        run: |
          if [[ ${{ inputs.package_man }} == "apt" ]]; then
            echo "UPDATE_COMMAND=apt update && apt upgrade -y" >> $GITHUB_ENV
          else
            echo "UPDATE_COMMAND=dnf update -y" >> $GITHUB_ENV
          fi

      - name: Install Distrobox
        run: curl -s https://raw.githubusercontent.com/89luca89/distrobox/main/install | sudo sh

      - name: Create Distrobox
        run: |
          distrobox create --name $CONTAINER_NAME --image ${{ inputs.distro }} \
            --additional-packages "git systemd ${{ inputs.package_man }} sudo $ADDITIONAL_PKG" \
            --init-hooks "$UPDATE_COMMAND" \
            --init --pull --root --unshare-all \
            --additional-flags "--userns=keep-id" --additional-flags "--user 0" \
            --absolutely-disable-root-password-i-am-really-positively-sure
      
      - name: Clone FOG
        run: distrobox enter --root $CONTAINER_NAME -- git clone -b working-1.6 https://github.com/FOGProject/fogproject.git
      
      - name: Install FOG
        run: distrobox enter --root $CONTAINER_NAME -- bash -c 'sudo ./fogproject/bin/installfog.sh -y'
